version: "3"
services:
  mysql:
    #image: mysql:5.7
    build: 
      context: ./services/mysql
      dockerfile: Dockerfile
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app3"
      MYSQL_USER: "app3"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./services/mysql/data:/var/lib/mysql
    ports:
      - "6309:3306"
    networks:
      - docker-disnet
  redis:
    image: redis:4.0.2
    ports:
      - "6481:6379"
    networks:
      - docker-disnet
  php:
    build: 
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ../../app/app3:/www/html/app
    ports:
      - "9093:9000"
    networks:
      - docker-disnet
  nginx:
    image: nginx:1.12.2
    ports:
      - "8083:80"
    depends_on:
      - php
    volumes:
      - ./services/nginx/config:/etc/nginx/conf.d
      - ./services/nginx/logs:/etc/nginx/logs/
      - ../../app/app3:/www/html/app
    networks:
      - docker-disnet

volumes:
 mysql:
   driver: local
networks:
  default:
    external: false
  docker-disnet:
    external: true